keys:
  - &laptop age132q904eh8nk60sxel90e6n09k0sq6u4908sxz87gf33lwlgpwu6qeuvr49
  - &immich age1lvx0sy27p8gj4e8c4dw3tz5njyk975xtvl5rwr5fvyx7rqzg4uuqv6gkqq
  - &caddy age1h9eg8cl50usge2e5sjr77pes2l0wgl3ypk95jd4w32m88yhpugnsd9dpl4
  - &uptime-kuma age1z8939t5qwrcg0huvwhh0ldpzgedl9ugcufm40wj6dnu0cnptte5sw8m9sh
  - &paperless age1yfuu9700ddt6xyle3s4fvmpsp2nx3css2cu0e63lc4x5qr6l2arsszjj49
  - &claude-agent age1z8939t5qwrcg0huvwhh0ldpzgedl9ugcufm40wj6dnu0cnptte5sw8m9sh
  - &photosdotmcneill age1rvkhelafufc4l2lc780fp22uw0cckhfam4wrsgdmcr7jk6ctcypqe83787

creation_rules:
  - path_regex: .*secrets/immich\.yaml$
    key_groups:
      - age:
          - *laptop
          - *immich
  - path_regex: .*secrets/caddy\.yaml$
    key_groups:
      - age:
          - *laptop
          - *caddy
  - path_regex: .*secrets/uptime-kuma\.yaml$
    key_groups:
      - age:
          - *laptop
          - *uptime-kuma
  - path_regex: .*secrets/paperless\.yaml$
    key_groups:
      - age:
          - *laptop
          - *paperless
  - path_regex: .*secrets/claude-agent\.yaml$
    key_groups:
      - age:
          - *laptop
          - *claude-agent
  - path_regex: .*secrets/photosdotmcneill\.yaml$
    key_groups:
      - age:
          - *laptop
          - *photosdotmcneill
  - path_regex: .*secrets/gb-grid\.yaml$
    key_groups:
      - age:
          - *laptop
