{ lib
, buildDotnetModule
, fetchFromGitHub
, fetchurl
, dotnetCorePackages
, protobuf
, grpc
, stdenv
, icu
, openssl
, zlib
, krb5
, fontconfig
}:

# Network Optimizer for UniFi (https://github.com/Ozark-Connect/NetworkOptimizer)
# Built from source: upstream publishes no prebuilt Linux tarball of the web
# app (only the Windows MSI and the optional site agent).
buildDotnetModule rec {
  pname = "network-optimizer";
  version = "2.6.2";

  src = fetchFromGitHub {
    owner = "Ozark-Connect";
    repo = "NetworkOptimizer";
    rev = "v${version}";
    hash = "sha256-+Pmk7kHdd8ohhibeeTMgYD8Feui0DBPSkWWVAwd9Kik=";
  };

  projectFile = "src/NetworkOptimizer.Web/NetworkOptimizer.Web.csproj";
  # Generated by running this package's passthru.fetch-deps and converting the
  # JSON to nix — see network-optimizer-deps.nix header. The Blazor-ApexCharts
  # entry is special-cased: upstream ships that nupkg via an in-repo local feed
  # (packages/), not nuget.org, so fetchNuGet's default URL would 404.
  nugetDeps = ./network-optimizer-deps.nix;

  dotnet-sdk = dotnetCorePackages.sdk_10_0;
  dotnet-runtime = dotnetCorePackages.aspnetcore_10_0;

  # MinVer derives the version from git tags, which a tarball src doesn't
  # have — same override upstream's Dockerfile passes.
  dotnetFlags = [ "-p:MinVerVersionOverride=${version}" ];

  # Grpc.Tools' NuGet-bundled protoc/grpc plugin are glibc binaries and won't
  # run in the Nix sandbox — point the build at ours (same mechanism
  # upstream's arm64 Dockerfile path uses).
  PROTOBUF_PROTOC = "${lib.getExe' protobuf "protoc"}";
  PROTOBUF_GRPC_PLUGIN = "${lib.getExe' grpc "grpc_csharp_plugin"}";

  # Native libs the runtime P/Invokes (directly or via NuGet-bundled .so
  # files like e_sqlite3 / libSkiaSharp) that autoPatchelf must resolve.
  runtimeDeps = [
    stdenv.cc.cc.lib
    icu
    openssl
    zlib
    krb5
    fontconfig
  ];

  executables = [ "NetworkOptimizer.Web" ];

  # Speed-test helpers under tools/ (x64 runs here; arm64 is SFTP'd onto
  # gateways). why: docs/notes.md#network-optimizer
  postInstall =
    let
      uwnspeedtest = arch: hash: fetchurl {
        url = "https://github.com/Ozark-Connect/NetworkOptimizer/releases/download/v${version}/uwnspeedtest-linux-${arch}";
        inherit hash;
      };
    in ''
      mkdir -p $out/lib/network-optimizer/tools
      install -m755 ${uwnspeedtest "x64" "sha256-DP6fpet1qtwkoJBq+T9iSTOrgQJjdmlH/x2BALy4myY="} \
        $out/lib/network-optimizer/tools/uwnspeedtest-linux-x64
      install -m755 ${uwnspeedtest "arm64" "sha256-w98nws76qGYAmctN6xzCCCjhh3nhm2+S5XLr7+JXfh4="} \
        $out/lib/network-optimizer/tools/uwnspeedtest-linux-arm64
    '';

  meta = {
    description = "Security auditing, SQM, speed testing and monitoring for UniFi networks";
    homepage = "https://github.com/Ozark-Connect/NetworkOptimizer";
    license = lib.licenses.bsl11;
    mainProgram = "NetworkOptimizer.Web";
    platforms = [ "x86_64-linux" "aarch64-linux" ];
  };
}
