# NuGet dependencies for pkgs/network-optimizer.nix.
# Generated by the package's passthru.fetch-deps + this conversion; regenerate on
# version bumps and KEEP the Blazor-ApexCharts special case: upstream ships that nupkg
# via an in-repo local feed (packages/), not nuget.org, so fetchNuGet's default
# nuget.org URL would 404. Pinned to the release tag's raw file instead.
{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "BouncyCastle.Cryptography";
    version = "2.6.2";
    hash = "sha256-Yjk2+x/RcVeccGOQOQcRKCiYzyx1mlFnhS5auCII+Ms=";
  })
  (fetchNuGet {
    pname = "Castle.Core";
    version = "5.1.1";
    hash = "sha256-oVkQB+ON7S6Q27OhXrTLaxTL0kWB58HZaFFuiw4iTrE=";
  })
  (fetchNuGet {
    pname = "Castle.Core.AsyncInterceptor";
    version = "2.1.0";
    hash = "sha256-AiUf3sUARPuq4Z6mYfGEaBEVtB5RJAqSAaxg46RvW/A=";
  })
  (fetchNuGet {
    pname = "CsvHelper";
    version = "33.0.1";
    hash = "sha256-4MwA/WerpI0VYWiaEudNCNnE1v6/k2tPmLbRjmgijV4=";
  })
  (fetchNuGet {
    pname = "DnsClient";
    version = "1.8.0";
    hash = "sha256-Xc8BOCI9M8gSM5raVnPezA4yeO1eoyxXPPn9jh5/RaY=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.31.1";
    hash = "sha256-UEcn4H8F+zK0AjSmz1aTyyMksLxJOGNf2IROtF+DydA=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.35.1";
    hash = "sha256-a6UViZFeNkDh/904SGPdDXPwymqKrFkeyBxCxqPuVc4=";
  })
  (fetchNuGet {
    pname = "Grpc.AspNetCore";
    version = "2.80.0";
    hash = "sha256-ygEVOd03/17WCr4iUyG789j59zbFPSzb54fBGgwKT/U=";
  })
  (fetchNuGet {
    pname = "Grpc.AspNetCore.Server";
    version = "2.80.0";
    hash = "sha256-22j5qUW4nerTfZkVYnteO61sWY9l/Z8KWyhmX8kIJeE=";
  })
  (fetchNuGet {
    pname = "Grpc.AspNetCore.Server.ClientFactory";
    version = "2.80.0";
    hash = "sha256-Lmapi2fO+/FbSVkBe13CbQk5QiEwNYtQjXNV4IPWGC8=";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.80.0";
    hash = "sha256-OVFeykeI5HNVuktAw48tPVg46Lxek8WKmEYu0JvO26g=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Client";
    version = "2.80.0";
    hash = "sha256-yvPRt3Z4ARre65PKIFMAt8J1fMp/G7Oig55dvZPRQHI=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.ClientFactory";
    version = "2.80.0";
    hash = "sha256-2PjJub9d2KbxvsieULpdT35z7ZDMXttviuZGo+6saMQ=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Common";
    version = "2.80.0";
    hash = "sha256-T45jPSyl7psOufGGJv1o6ZyewvlGK2ZFRS8bhzNAh0E=";
  })
  (fetchNuGet {
    pname = "Grpc.Tools";
    version = "2.80.0";
    hash = "sha256-Dd8TuiCgllKHIXQinbWLP9Q2P9GYMxQt1j0cP5BHTSk=";
  })
  (fetchNuGet {
    pname = "Grpc.Tools";
    version = "2.81.1";
    hash = "sha256-5me0iCi6BXZMS7H/3MYy2Ao0ufpSTBmSfru3OVusoKc=";
  })
  (fetchNuGet {
    pname = "HtmlAgilityPack";
    version = "1.12.4";
    hash = "sha256-58ohjvtRXFwfY46Hny9GWL2r6KwZzkJWHFXwIWjkaHU=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core";
    version = "2.14.1";
    hash = "sha256-EXvojddPu+9JKgOG9NSQgUTfWq1RpOYw7adxDPKDJ6o=";
  })
  (fetchNuGet {
    pname = "InfluxDB.Client";
    version = "4.18.0";
    hash = "sha256-MARXEvxHUNQj5lkHQyOIgjLs47F+fL/PCPgn0AaLXKI=";
  })
  (fetchNuGet {
    pname = "InfluxDB.Client.Core";
    version = "4.18.0";
    hash = "sha256-Aeuby6+/LiqA6sIufOkJ5162l1ZksBjfX9sHZW1zlXM=";
  })
  (fetchNuGet {
    pname = "ITfoxtec.Identity.Saml2";
    version = "4.20.1";
    hash = "sha256-CtMz5cZ/BA+eRWZtpvudbOMJVtgDaCodbS+3Y9ZxriE=";
  })
  (fetchNuGet {
    pname = "ITfoxtec.Identity.Saml2.MvcCore";
    version = "4.20.1";
    hash = "sha256-VILFZot/h2nDhtrmMtpFdKrLAx7D5RDvESj56A1XWVo=";
  })
  (fetchNuGet {
    pname = "JsonSubTypes";
    version = "2.0.1";
    hash = "sha256-1Sh5MkvJfOVGo83D5EJJzmJYu5LFSOMAFwQCNRNvFc4=";
  })
  (fetchNuGet {
    pname = "Lextm.SharpSnmpLib";
    version = "12.5.7";
    hash = "sha256-x5XsC5gd77JPwYe0ViuVh71DxGc++XdqngmVJ1w9cHo=";
  })
  (fetchNuGet {
    pname = "MailKit";
    version = "4.16.0";
    hash = "sha256-4yyFxq8pJVTIgAJkyAYcuV2+/ZirENgUSk1OSD/gKIo=";
  })
  (fetchNuGet {
    pname = "MaxMind.Db";
    version = "4.1.0";
    hash = "sha256-cwYlgi7U7EN7g+WHv4Jmh16VUQvqqTUgHWCAIa+Z/Z4=";
  })
  (fetchNuGet {
    pname = "MaxMind.GeoIP2";
    version = "5.2.0";
    hash = "sha256-iuYNc0+MVS3JCL6ZZf72baG4ToaBohDLRSB3KNIx+sk=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Authentication.JwtBearer";
    version = "10.0.7";
    hash = "sha256-Y1DM6+4ji/xoAxv9NLsJOj7YUkQA5ItrlTR3NL2XcrE=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Authentication.OpenIdConnect";
    version = "10.0.7";
    hash = "sha256-hr1QgB9miQO2rXj5heibTX/fa3Tj/Nci8G/pDcrq11c=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Cryptography.Internal";
    version = "10.0.7";
    hash = "sha256-0Qoweg4yPoZ91js2jA7BKILw5A5fZceRaWHiCmAnAlY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Cryptography.KeyDerivation";
    version = "10.0.7";
    hash = "sha256-NTBG08n1iu3jKlXZfrZegtFeyJXN3r4RfBbrEGNSHY0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Identity.EntityFrameworkCore";
    version = "10.0.7";
    hash = "sha256-pRslL7n5Gil4vOzXgrwBnHTQ2C0sez0MglZ/r56x52c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Framework";
    version = "17.11.31";
    hash = "sha256-YS4oASrmC5dmZrx5JPS7SfKmUpIJErlUpVDsU3VrfFE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Framework";
    version = "18.0.2";
    hash = "sha256-fO31KAdDs2J0RUYD1ov9UB3ucsbALan7K0YdWW+yg7A=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.11.0";
    hash = "sha256-hQ2l6E6PO4m7i+ZsfFlEx+93UsLPo4IY3wDkNG11/Sw=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "5.0.0";
    hash = "sha256-g4ALvBSNyHEmSb1l5TFtWW7zEkiRmhqLx4XWZu9sr2U=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "5.0.0";
    hash = "sha256-ctBCkQGFpH/xT5rRE3xibu9YxPD108RuC4a4Z25koG8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Workspaces";
    version = "5.0.0";
    hash = "sha256-yWVcLt/f2CouOfFy966glGdtSFy+RcgrU1dd9UtlL/Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Workspaces.Common";
    version = "5.0.0";
    hash = "sha256-Bir5e1gEhgQQ6upQmVKQHAKLRfenAu60DAzNupNnZsQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Workspaces.MSBuild";
    version = "5.0.0";
    hash = "sha256-+58+iqTayTiE0pDaog1U8mjaDA8bNNDLA8gjCQZZudo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "10.0.7";
    hash = "sha256-UjaMWWznnRR57IUt24mMshqPFtEo9hX+9Bf4N1dwy0E=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore";
    version = "10.0.7";
    hash = "sha256-ujx4e1rgGtGdsGxKKO4K0JUHHQ15Jg4jSFVsMjdbXKA=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Abstractions";
    version = "10.0.7";
    hash = "sha256-hvMqfhPhGzM0RG5UmW1aLcRpUYwdprAd0lbLxRC5GR8=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Analyzers";
    version = "10.0.7";
    hash = "sha256-/o6FXF0ReWHe66VkhjgGepMruul3DGYXAe9L3fSxVBc=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Design";
    version = "10.0.7";
    hash = "sha256-r9k8A/yyYq18ABiqMyZXw23y2u4o0glQrqiOufvDjh0=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Relational";
    version = "10.0.7";
    hash = "sha256-PwUDxiyT3pLZlLO8/5Wq1ypHjuv15g+3IZPn9NdFC9g=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Sqlite";
    version = "10.0.7";
    hash = "sha256-Fwc1tRXxdJeblEQflr4xXtqIqePUBMVzr4ayvekTI+U=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Sqlite.Core";
    version = "10.0.7";
    hash = "sha256-AkwUW69bhK9qbLd42BQSREwZuhqDD+PS3w0DGX8I8rM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Abstractions";
    version = "10.0.7";
    hash = "sha256-u3pHlFaDPeY2v89jNYLiHUQ2aGMKpe5wpXZUt8hkgdE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Memory";
    version = "10.0.7";
    hash = "sha256-8qXL1F5gE9OZUEp/9pNVT33hjRMVAPt4eovT1NesKoQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "10.0.7";
    hash = "sha256-2RqDs7+dXtGY78E5jSd1qyKu+dMQkbzv+oMY09SEJm0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "10.0.7";
    hash = "sha256-MnUJzZYnl089xuVi6kpt9kymBIvYun9U+Itd12dM5Co=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "10.0.7";
    hash = "sha256-lU4G801+Cy3ua+S2slY5UVHOPXdF0I7r3lYX38mQSPw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "10.0.7";
    hash = "sha256-dICogdaqa5mHqyvFA0lTomFa39Dqm4nn7Pit6qi6eQY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "9.0.0";
    hash = "sha256-dAH52PPlTLn7X+1aI/7npdrDzMEFPMXRv4isV1a+14k=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "10.0.7";
    hash = "sha256-uQmTQarMn0fuZV03MyCb78Ex+96cuqFHNO5SyFOPkJk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "9.0.0";
    hash = "sha256-CncVwkKZ5CsIG2O0+OM9qXuYXh3p6UGyueTHSLDVL+c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "10.0.0";
    hash = "sha256-oCcIjmwH8H0n9bT3wQBWdotMvYuoiazfiKrXAs2bLiI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "10.0.7";
    hash = "sha256-ZPL20hmZmttPGjiF3zAVyB/0o9VBOSBwi6sF0/084KA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics";
    version = "10.0.7";
    hash = "sha256-Sd0ZsXgO7w/35vOKN1B0CZdcIcMJnf/Z/8POSikTyRk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "10.0.7";
    hash = "sha256-ocntk68Qa3ccHGEnzmZuKdBWdQEnp4PgwJk63bSRjDA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "10.0.7";
    hash = "sha256-ibxSdxibq1UKOo4Mz+zthbZd0UUFipnJNb0hPwvEXCA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "10.0.7";
    hash = "sha256-S1WAgBHPi7H71uQUGyl2aG/IITgYfVNznyXsFrRe/kE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.WindowsServices";
    version = "10.0.7";
    hash = "sha256-v2B//JKXSH4tW9aX6jBqqfX5oXi5mY4ezRzIVrBikI8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "10.0.7";
    hash = "sha256-cbTDyODUPitTBOn88A5R5/QGPzOTCT7qeyP2gG6WOS0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Identity.Core";
    version = "10.0.7";
    hash = "sha256-K30004GN4w7knDVeDQ0QpL7J46gWZJN2oY7sqP0rIN4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Identity.Stores";
    version = "10.0.7";
    hash = "sha256-Apj0lz0riP+gomKZHTqIkF4YFhnc22ouJ1+Oi3a8VYs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "10.0.7";
    hash = "sha256-AUOet0nWZHB132XCPuyUp5xTFNnWjHhoOtzooFcXHk4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "9.0.0";
    hash = "sha256-kR16c+N8nQrWeYLajqnXPg7RiXjZMSFLnKLEs4VfjcM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "10.0.7";
    hash = "sha256-/ITLUXgcs5tRDdeileNlmNB92V25CRd1FGBocChJj0g=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "10.0.7";
    hash = "sha256-bgfSy30lXJhN9T+CWdwodnpZJDLJoElM4HKOOCijjfo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "10.0.7";
    hash = "sha256-qR7NQaCsOdH++AviTzz4J6D6pak/YVjih2aZqYc22d8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "8.0.8";
    hash = "sha256-9AZmxZ4YcUgHOxxdmklJdIlQSGg7C9BLVz9cvaDdu5c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "10.0.7";
    hash = "sha256-XtyfdZ26kjnuCF/YHbdGdsIeR/nxSW7yyQZ04sOa9RU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.0";
    hash = "sha256-n2m4JSegQKUTlOsKLZUUHHKMq926eJ0w9N9G+I3FoFw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "9.0.0";
    hash = "sha256-DT5euAQY/ItB5LPI8WIp6Dnd0lSvBRP35vFkOXC68ck=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "10.0.7";
    hash = "sha256-6UBnB1ouWwRkVEGt5xLfXZvpYsCQQJijKvBlBCJOmmM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "10.0.7";
    hash = "sha256-cQBhL1IkRl1lxaZImAZBVS39CfWkB+J6+hJVEVBE35I=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "2.2.0";
    hash = "sha256-DMCTC3HW+sHaRlh/9F1sDwof+XgvVp9IzAqzlZWByn4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "9.0.0";
    hash = "sha256-ZNLusK1CRuq5BZYZMDqaz04PIKScE2Z7sS2tehU7EJs=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "8.18.0";
    hash = "sha256-mkguJA4aXIVVQvSJ9Duq9mivbGXAIkLQp3a8PKy223A=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "8.18.0";
    hash = "sha256-MdqY9CGRs+fTLb3HYYcSfuzqDFo4Dpho4McFWWferjA=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "8.18.0";
    hash = "sha256-09WyYskyL8gjjVDzoZBQAGXgsPmyagWftALSBCdt4gg=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Protocols";
    version = "8.18.0";
    hash = "sha256-WoRqEJYkNNX358CzplvlzSFweqUC21Cv31i1ucAzd+g=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Protocols.OpenIdConnect";
    version = "8.18.0";
    hash = "sha256-L3kUWV1l6K44h69GXYhZ76fBK9mQ8qB4i1+V9MdkWRs=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "8.18.0";
    hash = "sha256-sFhonZW9G6H4ooQ6N/78fkZvADZ2Hf5WAS3FKd/ue1E=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens.Saml";
    version = "8.18.0";
    hash = "sha256-0ATD4QFu3yubcUon3fT2+/AzsGFIMZcB2cma0yaQV9U=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Xml";
    version = "8.18.0";
    hash = "sha256-s+w6y9r4TE0kmE4RRE9Vl55+RS08Kxlm4ppGh4txWCY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Net.Http.Headers";
    version = "2.2.8";
    hash = "sha256-SWbUkzmpOFp/r6vW3wiOAf2ce5OkZSmJ9quWbT4yFug=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.SolutionPersistence";
    version = "1.0.52";
    hash = "sha256-KZGPtOXe6Hv8RrkcsgoLKTRyaCScIpQEa2NhNB3iOXw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "6.0.0";
    hash = "sha256-N9EVZbl5w1VnMywGXyaVWzT9lh84iaJ3aD48hIBk1zA=";
  })
  (fetchNuGet {
    pname = "MimeKit";
    version = "4.16.0";
    hash = "sha256-yWGXVm+EHvBSsZlVHdWdD+rVwdf/5hHxsUfJMSd2Afo=";
  })
  (fetchNuGet {
    pname = "MinVer";
    version = "6.1.0";
    hash = "sha256-/lF5o5+OOQ+GchtNGYafT8uXslWUoIWJaHuklgE0R28=";
  })
  (fetchNuGet {
    pname = "Mono.TextTemplating";
    version = "3.0.0";
    hash = "sha256-VlgGDvgNZb7MeBbIZ4DE2Nn/j2aD9k6XqNHnASUSDr0=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "NodaTime";
    version = "3.0.0";
    hash = "sha256-kOiGkTez5eIWsBJVYURe8WRuyIhQgMiq/c/m42+XZuY=";
  })
  (fetchNuGet {
    pname = "NodaTime";
    version = "3.1.11";
    hash = "sha256-ZvJlCEjq61KS3qr4Lw/C+yyagic4rESZ7qa0RGul/sU=";
  })
  (fetchNuGet {
    pname = "NodaTime.Serialization.JsonNet";
    version = "3.1.0";
    hash = "sha256-2+TtzbvpPUr298T05IAsIRZuZxXHJBZhxLrgmngHYOM=";
  })
  (fetchNuGet {
    pname = "Polly";
    version = "7.1.0";
    hash = "sha256-rnp9GSJsm0BScqBlECaJCmtY1ThhrL1pKVHm3ix+p5c=";
  })
  (fetchNuGet {
    pname = "Polly";
    version = "8.6.5";
    hash = "sha256-2YRacrP3b3C6EBCb5Pjg6fQdGj+SgbTeaWHN/oZ1d8s=";
  })
  (fetchNuGet {
    pname = "Polly.Core";
    version = "8.6.5";
    hash = "sha256-m12obNfMZdWQWJoCaF03H5qEbFDdp9FSdHTHcIIsACQ=";
  })
  (fetchNuGet {
    pname = "Polly.Extensions.Http";
    version = "3.0.0";
    hash = "sha256-m/DfApduj4LIW9cNjUGit703sMzMLz0MdG0VXQGdJoA=";
  })
  (fetchNuGet {
    pname = "QRCoder";
    version = "1.8.0";
    hash = "sha256-UvOeFFxUZ/bddmDs6IamiYGDIfgxybE/CSpPyy5DMxI=";
  })
  (fetchNuGet {
    pname = "QuestPDF";
    version = "2025.12.1";
    hash = "sha256-9nE6AZdmIAZ9tKBlway+hE7djyEGo1KYjzteetErxY8=";
  })
  (fetchNuGet {
    pname = "RestSharp";
    version = "112.0.0";
    hash = "sha256-p0H29uL5M6JqSdhCcNcU5Pvz+rrZd+tmcGycXioZVhk=";
  })
  (fetchNuGet {
    pname = "Scriban";
    version = "7.2.5";
    hash = "sha256-E1APWeX7IShpIin1jtKhKc2C3nmcoJO/T9E87SO1IKw=";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.0.0";
    hash = "sha256-j8hQ5TdL1TjfdGiBO9PyHJFMMPvATHWN1dtrrUZZlNw=";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.2.0";
    hash = "sha256-7f3EpCsEbDxXgsuhE430KVI14p7oDUuCtwRpOCqtnbs=";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.3.0";
    hash = "sha256-jyIy4BjsyFXge3aO4GRFAdnX4/rz1MHfBkBDIpCDsTw=";
  })
  (fetchNuGet {
    pname = "Serilog.AspNetCore";
    version = "10.0.0";
    hash = "sha256-z7dY6pY2Kkns20mpzZN2GOfV172gDWpamKDXHyLhEJs=";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Hosting";
    version = "10.0.0";
    hash = "sha256-zFQMZkAPqg+j2ZI0oBN07hO+9MFiyy5YECRbz7msxeU=";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Logging";
    version = "10.0.0";
    hash = "sha256-MgfWK/SJWUPxPzrnCUnxn6Sy+SBVmP3dYd60uy80NdE=";
  })
  (fetchNuGet {
    pname = "Serilog.Formatting.Compact";
    version = "3.0.0";
    hash = "sha256-nejEYqJEMG9P2iFZvbsCUPr5LZRtxbdUTLCI9N71jHY=";
  })
  (fetchNuGet {
    pname = "Serilog.Settings.Configuration";
    version = "10.0.0";
    hash = "sha256-WJK+wR7XPGAtD+vO+pjF5mn4qy8tO5uWIqHhovL0lAs=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Console";
    version = "6.1.1";
    hash = "sha256-CfIg4Us4kSMQAn6rU2rsAeE22g6MpFiZdhoZWySpZeY=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Debug";
    version = "3.0.0";
    hash = "sha256-7/LmoRF1rUDFhJ47bTRQQFRgSHnZDO8484r3sCGqYvE=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.File";
    version = "7.0.0";
    hash = "sha256-LxZYUoUPkCjIIVarJilnXnqQiMrFNJtoRilmzTNtUjo=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlite3";
    version = "2.1.11";
    hash = "sha256-kWRapMTVEfcc0DxnI9Ai1+RwAAcR2+HUu+WF+OeLJCs=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlite3";
    version = "2.1.12";
    hash = "sha256-qaBua1oxP27zZ1+RmX0BKt7/6KqeH/1p7Uak5oWwVOE=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.1.11";
    hash = "sha256-s/fxEoYlNf9c2C4HZueMzPCBvpiViDVlSpg7epB0GXY=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.1.12";
    hash = "sha256-rwaQQTj/ptyVpZkTPWTSVHFtb6zHVDprO5EHk9rp3KU=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.lib.e_sqlite3";
    version = "2.1.12";
    hash = "sha256-SiLAL/z0iXkpA88mPe+fzidzlxaIP5ZfC17v8WN0MKw=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.provider.e_sqlite3";
    version = "2.1.12";
    hash = "sha256-3ysycZkuXXGRhsRnHjz0+GWAl8FUy81BSUq1lMWZdZU=";
  })
  (fetchNuGet {
    pname = "SSH.NET";
    version = "2025.1.0";
    hash = "sha256-vtpvE5B+IxoMkq9CQMehoR5ZRtihaHQ4VyhmkkIjL98=";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "6.0.0";
    hash = "sha256-uPetUFZyHfxjScu5x4agjk9pIhbCkt5rG4Axj25npcQ=";
  })
  (fetchNuGet {
    pname = "System.Composition";
    version = "9.0.0";
    hash = "sha256-FehOkQ2u1p8mQ0/wn3cZ+24HjhTLdck8VZYWA1CcgbM=";
  })
  (fetchNuGet {
    pname = "System.Composition.AttributedModel";
    version = "9.0.0";
    hash = "sha256-a7y7H6zj+kmYkllNHA402DoVfY9IaqC3Ooys8Vzl24M=";
  })
  (fetchNuGet {
    pname = "System.Composition.Convention";
    version = "9.0.0";
    hash = "sha256-tw4vE5JRQ60ubTZBbxoMPhtjOQCC3XoDFUH7NHO7o8U=";
  })
  (fetchNuGet {
    pname = "System.Composition.Hosting";
    version = "9.0.0";
    hash = "sha256-oOxU+DPEEfMCuNLgW6wSkZp0JY5gYt44FJNnWt+967s=";
  })
  (fetchNuGet {
    pname = "System.Composition.Runtime";
    version = "9.0.0";
    hash = "sha256-AyIe+di1TqwUBbSJ/sJ8Q8tzsnTN+VBdJw4K8xZz43s=";
  })
  (fetchNuGet {
    pname = "System.Composition.TypedParts";
    version = "9.0.0";
    hash = "sha256-F5fpTUs3Rr7yP/NyIzr+Xn5NdTXXp8rrjBnF9UBBUog=";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "8.0.0";
    hash = "sha256-xhljqSkNQk8DMkEOBSYnn9lzCSEDDq4yO910itptqiE=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "8.0.0";
    hash = "sha256-rt8xc3kddpQY4HEdghlBeOK4gdw5yIj4mcZhAVtk2/Y=";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "6.0.0";
    hash = "sha256-/9EaAbEeOjELRSMZaImS1O8FmUe8j4WuFUw1VOrPyAo=";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "8.18.0";
    hash = "sha256-90vrFrRi93g0HuPsUpjt/Aa01l8Jpi1z9hgMB3wIaxs=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.1";
    hash = "sha256-Lo5UMqp8DsbVSUxa2UpClR1GoYzqQQcSxkfyFqB/d4Q=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "10.0.0";
    hash = "sha256-d3sLG+LZ3+N/h/6gdJcVKOgbBO6wYb66NfXalAEDqnE=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "8.0.0";
    hash = "sha256-fb0pa9sQxN+mr0vnXg1Igbx49CaOqS+GDkTfWNboUvs=";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.Primitives";
    version = "10.0.652802";
    hash = "sha256-HeTZi2oJJkq9GpfAYBp8gA0cLZiKmFJ6/sjtqvXjCCI=";
  })
  (fetchNuGet {
    pname = "System.ServiceProcess.ServiceController";
    version = "10.0.7";
    hash = "sha256-koSlZI43JaCrG3ultJ6Sj7Ic9D9N878L+6HtRRGyJSA=";
  })
  # In-repo local feed package (see header).
  (fetchNuGet {
    pname = "Blazor-ApexCharts";
    version = "6.1.1-ozarkconnect.2";
    url = "https://raw.githubusercontent.com/Ozark-Connect/NetworkOptimizer/v2.6.2/packages/Blazor-ApexCharts.6.1.1-ozarkconnect.2.nupkg";
    hash = "sha256-TPZVpA/7L6p4rd3idUbYVzX7tjHOTpszbqYfCapwD4w=";
  })
]
