# minihutch baremetal hardware.
#
# Generated by `nixos-generate-config --no-filesystems --root /mnt` on the
# live ISO, 2026-08-09, on the actual box (Intel N100, 8G RAM, Crucial
# CT1000P310SSD2 931.5G NVMe). `--no-filesystems` matters: the boot drive
# layout is owned by hardware/minihutch-disko.nix, and a generated
# fileSystems block would collide with it.
#
# Differences from hutch's, for reference: no `ahci` (NVMe only, no SATA),
# no `usbhid`, plus `sdhci_pci` for the onboard SD reader.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
